<?php
/** @var \Nans\Faq\Block\Frontend\Question $block */
?>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "questions": {
                    "component"     : "Nans_Faq/js/faq_model",
                    "baseUrl"       : "<?=$block->getBaseUrl()?>",
                    "apiUrl"        : "<?=$block->getApiUrl()?>",
                    "storeId"       : <?=$block->getStoreId()?>
                }
            }
        }
    }
}
</script>

<div id="trip-builder-wrapper" data-bind="scope: 'questions'">
    <!-- ko if: dataLoaded -->
    <!-- ko foreach: categories -->
    <p><span data-bind="text:title"></span> - <span data-bind="text:sortOrder"></span></p>
    <!-- ko foreach: questions -->
    <p><span data-bind="text:title"></span> - <span data-bind="text:sortOrder"></span></p>
    <!-- /ko -->
    <!-- /ko -->
    <!-- /ko -->
</div>